# bStats (https://bStats.org) collects some basic information for plugin authors, like how
# many people use their plugin and their total player count. It's recommended to keep bStats
# enabled, but if you're not comfortable with this, you can turn this setting off. There is no
# performance penalty associated with having metrics enabled, and data sent to bStats is fully anonymous.

version: 1.6

# Some info in the config have been typed shorter so as not to clutter it too much. Please visit for more detailed explanations with examples:
# https://github.com/JeannotM/DynamicDifficulty or https://www.spigotmc.org/resources/dynamic-difficulty.92025/

# Affinity Gained or Lost When Doing Certain Things.
points-per-minute: 3
block-mined: 2
player-hit: -1
affinity-per-heart-loss: -1 # So 1.5 hearts of damage (counts as 2 hearts) amounts to (-1 * 2) = -2 affinity
pve-kill: 2
death: -100

# How Much Affinity a Player Starts With When Joining For The First Time.
starting-affinity: 600

# To set custom min and max affinity when players start playing for the first time
starting-min-affinity: -1
starting-max-affinity: -1

# What The Maximum and Minimum Affinity Are, no one can get more or less than this (even with commands)
min-affinity: 0
max-affinity: 1500

# Mobs that will give affinity, Will use "pve-kill" if no value was specified: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
# - MOBTYPE: <Affinity points>
mobs-count-as-pve:
- BLAZE: 4
- CAVE_SPIDER: 3
- CREEPER: 3
- DROWNED
- ENDER_DRAGON: 100
- ELDER_GUARDIAN: 20
- ENDERMAN: 5
- GUARDIAN: 3
- HUSK
- IRON_GOLEM: 50
- MAGMA_CUBE
- PHANTOM
- PLAYER: 20
- PIGLIN
- PIGLIN_BRUTE: 5
- SKELETON
- SPIDER
- VILLAGER: 20
- VINDICATOR: 5
- WARDEN: 200
- WITCH
- WITHER: 100
- WITHER_SKELETON: 5
- ZOMBIE

# Blocks that will give affinity, Will use "block-mined" if no value was specified: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# - BLOCKTYPE: <Affinity points>
blocks:
- ANCIENT_DEBRIS: 4
- DEEPSLATE_DIAMOND_ORE
- DIAMOND_ORE
- EMERALD_ORE

toggle-settings:
  difficulty-type: player # Supported: player
  silk-touch-allowed: false # Whether the Player Will Receive Affinity When Mining Blocks With Silk Touch
  prevent-affinity-loss-on-suicide: true # People won't lose affinity if they die by their own hands.
  loot-changes-to-spawned-mobs: false # Mobs that spawn from eggs or spawners, won't have damage, loot or other changes. Players will also NOT receive any Affinity from these mobs.
  allow-tamed-wolves-in-calculations: true # Whether to allow tamed wolves in the damage calculations
  force-hard-difficulty: true # Forces hard Difficulty on all worlds that are not in "disabled-worlds"
  advanced:
    # advanced features may decrease performance or are a little harder to configure
    custom-enchants-on-mobs: true
    exact-percentage: true # Calculates the percentage between 2 difficulties so the progression will feel more natural

saving-data:
  type: file # Supported: none, file, mysql, sqlite, mongodb, postgresql
#  port: 3306
#  host: localhost
#  username: root
#  password:
#  database: dynamicdifficulty

# You can disable DynamicDifficulty in certain worlds
disabled-worlds:
- example_name_test

# These mobs ignore everything except the "effects-when-attacked" and "mobs-ignore-player" settings from difficulty
disabled-mobs:
- ENDER_DRAGON
- ENDER_CRYSTAL
- ELDER_GUARDIAN
- WARDEN
- WITHER

# This has been calculated from the hard difficulty. So it is recommended to change these if you're not playing on hard world difficulty
# More information if you want to make your own difficulty (I'd recommend copying one of the other difficulties and changing values):
# <custom_name>:
#   enabled: <bool, Whether this difficulty is enabled>
#   affinity-required: <number, At What affinity this difficulty starts working>
#   damage-done-by-mobs: <percentage, How much damage mobs do to you>
#   damage-done-on-mobs: <percentage, How much damage you do on mobs>
#   hunger-drain-chance: <percentage, Chance that the hunger of a player will drain>
#   damage-done-by-ranged-mobs: <percentage, How much damage projectiles do>
#   double-durability-damage-chance: <percentage, Chance to take double damage on item durability>
#   chance-cancel-death: <number, Chance to cancel death when attack by a entity>
#   minimum-health-starvation: <number, Minimum hearts left from starvation damage>
#   maximum-health: <number, Maximum health when a player is in this difficulty>
#   experience-multiplier: <percentage, Experience Multiplier>
#   double-loot-chance: <percentage, Chance to double the loot dropped when a mob is killed or an ore that is mined>
#   keep-inventory: <bool, Whether the player keeps everything on death or not>
#   allow-pvp: <bool, Whether the player can attack or be attacked by other players>
#   allow-natural-regen <bool, Whether health regen from 'natural occurrences' (full foodbar) should be allowed.
#   effects-when-attacked: <bool, Whether you get poison/wither etc from mob attacks (not including splash potions), works only on normal/hard world difficulty>
#   prefix: <text, prefix to return if PlaceholderAPI is enabled>
#   commands-not-allowed-on-difficulty: <list, What commands aren't allowed to be run by players on certain difficulties, spaces not recommended>
#   extra-damage-for-certain-armor-types: <list, how much damage reduction/increased per armor set worn (full diamond on Hard = 100 + (4 x 4)). Settings include: [nothing, leather, golden, chainmail, iron, turtle, elytra, diamond and netherite]>
#   mobs-ignore-player: <list, these mobs will ignore the players unless they're provoked>
#   enchanting: <Will only work if 'custom-enchants-on-mobs' in the toggle-settings is enabled>
#     max-enchants: <number, Maximum amount of enchants on armor or weapons>
#     max-level: <number, Maximum level of the enchants>
#     chance-to-have-armor: <percentage, Chance for a mob to spawn with armor>
#     chance-to-enchant-a-piece: <percentage, Chance for a piece to be enchanted>
#     armor-drop-chance: <percentage, Chance to drop a piece of armor if killed>
#     weapon-drop-chance: <percentage, Chance to drop the weapon if killed>
#     weapon-chance: <percentage, Chance for a mob to spawn with weapons if armor is allowed>
#     helmet-chance: <percentage, Chance for a mob to have a helmet if armor is allowed>
#     chest-chance: <percentage, Chance for a mob to have a chestplate if armor is allowed>
#     leggings-chance: <percentage, Chance for a mob to have a leggings if armor is allowed>
#     boots-chance: <percentage, Chance for a mob to have a boots if armor is allowed>
difficulty:
  Easy:
    enabled: true
    affinity-required: 0
    damage-done-by-mobs: 50
    damage-done-on-mobs: 100
    damage-done-on-tamed: 75
    hunger-drain-chance: 60
    damage-done-by-ranged-mobs: 75
    double-durability-damage-chance: 0
    chance-cancel-death: 0.5
    minimum-health-starvation: 2
    maximum-health: 20
    experience-multiplier: 70
    double-loot-chance: 0
    allow-pvp: true
    keep-inventory: true
    allow-natural-regen: true
    effects-when-attacked: false
    prefix: '&7&l[&b&lEasy&7&l]&r'
    extra-damage-for-certain-armor-types:
      nothing: -3
      leather: -1
    mobs-ignore-player:
    - CREEPER
    enchanting:
      max-enchants: 1
      max-level: 1
      chance-to-have-armor: 5.0
      chance-to-enchant-a-piece: 15
      armor-drop-chance: 10.0
      weapon-drop-chance: 5.0
      weapon-chance: 1.0
      helmet-chance: 100.0
      chest-chance: 75.0
      leggings-chance: 56.25
      boots-chance: 42.19
  Normal:
    enabled: true
    affinity-required: 400
    damage-done-by-mobs: 75
    damage-done-on-mobs: 100
    damage-done-on-tamed: 100
    hunger-drain-chance: 80
    damage-done-by-ranged-mobs: 100
    double-durability-damage-chance: 1
    chance-cancel-death: 0.0
    minimum-health-starvation: 1
    maximum-health: 20
    experience-multiplier: 90
    double-loot-chance: 0
    allow-pvp: true
    keep-inventory: false
    allow-natural-regen: true
    effects-when-attacked: true
    prefix: '&7&l[&9&lNormal&7&l]&r'
    enchanting:
      max-enchants: 2
      max-level: 1
      chance-to-have-armor: 15.0
      chance-to-enchant-a-piece: 30
      armor-drop-chance: 15.0
      weapon-drop-chance: 10.0
      weapon-chance: 2.0
      helmet-chance: 100.0
      chest-chance: 75.0
      leggings-chance: 56.25
      boots-chance: 42.19
  Hard:
    enabled: true
    affinity-required: 1100
    damage-done-by-mobs: 100
    damage-done-on-mobs: 100
    damage-done-on-tamed: 100
    hunger-drain-chance: 100
    damage-done-by-ranged-mobs: 125
    double-durability-damage-chance: 5
    chance-cancel-death: 0.0
    minimum-health-starvation: 0
    maximum-health: 20
    experience-multiplier: 125
    double-loot-chance: 5
    allow-pvp: true
    keep-inventory: false
    allow-natural-regen: true
    effects-when-attacked: true
    prefix: '&7&l[&4&lHard&7&l]&r'
    commands-not-allowed-on-difficulty:
      - gotohome
      - help 34
    extra-damage-for-certain-armor-types:
      golden: 1
      chainmail: 1
      iron: 2
      diamond: 4
      netherite: 5
    enchanting:
      max-enchants: 3
      max-level: 2
      chance-to-have-armor: 20.0
      chance-to-enchant-a-piece: 45
      armor-drop-chance: 20.0
      weapon-drop-chance: 15.0
      weapon-chance: 5.0
      helmet-chance: 100.0
      chest-chance: 90.0
      leggings-chance: 81.0
      boots-chance: 72.9

custom-mob-items-spawn-chance:
  override-default-limits: false # will allow higher levels than Minecraft's defaults. (E.g. Unbreaking 7 can happen if max-level is higher or equals 7)
  override-enchant-conflicts: false # Allows conflicting enchants to occur on a single armor (E.g. Protection & Fire Protection)
  # These are the only mobs that will spawn with these custom settings
  # You can add any mob you want, but some will not show any armor. So it's not recommended going too wild
  includes-mobs:
  - ZOMBIE
  - SKELETON
  weapons-include:
  - WOODEN_SHOVEL: 200
  - GOLDEN_SHOVEL: 50
  - IRON_SHOVEL: 5
  - WOODEN_AXE: 200
  - GOLDEN_AXE: 50
  - IRON_AXE: 5
  - WOODEN_PICKAXE: 200
  - GOLDEN_PICKAXE: 50
  - IRON_PICKAXE: 5
  - WOODEN_SWORD: 200
  - GOLDEN_SWORD: 50
  - IRON_SWORD: 5
  armor-set-weight:
    leather: 3706
    golden: 4872
    chainmail: 1290
    iron: 127
    diamond: 4
    netherite: 1
  # https://www.digminecraft.com/lists/enchantment_list_pc.php
  # You'll have to use the names that are beneath the names with those __snakes__
  helmet-enchants-include:
  #- <ENCHANT_NAME>: WEIGHT, higher means more likely to occur, no value = weight of 1
  - protection: 10
  - blast_protection: 5
  - fire_protection: 5
  - projectile_protection: 5
  - vanishing_curse
  - binding_curse
  - aqua_affinity: 2
  - thorns
  - respiration: 2
  - unbreaking: 5
  chestplate-enchants-include:
  - protection: 10
  - blast_protection: 5
  - fire_protection: 5
  - projectile_protection: 5
  - vanishing_curse
  - binding_curse
  - thorns
  - unbreaking: 5
  leggings-enchants-include:
  - protection: 10
  - blast_protection: 5
  - fire_protection: 5
  - projectile_protection: 5
  - vanishing_curse
  - binding_curse
  - thorns
  - unbreaking: 5
  boots-enchants-include:
  - protection: 10
  - blast_protection: 5
  - fire_protection: 5
  - projectile_protection: 5
  - vanishing_curse
  - binding_curse
  - feather_falling: 5
  - thorns
  - frost_walker: 2
  - soul_speed
  - depth_strider: 2
  - unbreaking: 5
  weapon-enchants-include:
  - sharpness: 10
  - bane_of_arthropods: 5
  - smite: 5
  - fire_aspect: 2
  - looting: 2
  - knockback: 2
  - sweeping: 2
  - vanishing_curse
  - binding_curse
  - unbreaking: 5
  bow-enchants-include:
  - power: 10
  - flame: 2
  - infinity
  - punch: 2
  - vanishing_curse
  - binding_curse
  - unbreaking: 5